from __future__ import annotations

from dataclasses import dataclass

DIFFICULTY_LABELS = {
    "easy": "Easy",
    "normal": "Normal",
    "hard": "Hard",
}
LEADERBOARD_PERIOD_LABELS = {
    "season": "Weekly Season",
}
LEADERBOARD_PERIOD_ORDER = tuple(LEADERBOARD_PERIOD_LABELS.keys())
LEADERBOARD_DIFFICULTY_FILTER_LABELS = {
    "all": "All Difficulties",
    "easy": "Easy Only",
    "normal": "Normal Only",
    "hard": "Hard Only",
    "unknown": "Unknown Difficulty",
}
LEADERBOARD_DIFFICULTY_FILTER_ORDER = ("all", "easy", "normal", "hard")
LEADERBOARD_VERIFICATION_LABELS = {
    "verified": "Verified",
    "suspicious": "Suspicious",
}
ISSUE_STATUS_LABELS = {
    "all": "All Statuses",
    "investigating": "Investigating",
    "resolved": "Resolved",
}
ISSUE_STATUS_ORDER = ("all", "investigating", "resolved")
RUN_POWERUP_LABELS = {
    "magnet": "Magnet",
    "jetpack": "Jetpack",
    "mult2x": "Double Score",
    "sneakers": "Super Sneakers",
    "pogo": "Pogo Stick",
    "hoverboard": "Hoverboard",
}
SPECIAL_ITEM_LABELS = {
    "phantom_step": "Phantom Step",
    "afterimage_dash": "Afterimage Dash",
    "crowd_jammer": "Crowd Jammer",
    "impact_foam": "Impact Foam",
    "overclock_key": "Overclock Key",
    "magnet_echo": "Magnet Echo",
    "quiet_jet": "Quiet Jet",
    "combo_battery": "Combo Battery",
    "hyper_sneakers": "Hyper Sneakers",
    "risk_converter": "Risk Converter",
    "jackpot_fuse": "Jackpot Fuse",
    "chain_saver": "Chain Saver",
    "vault_seal": "Vault Seal",
    "season_imprint": "Season Imprint",
}
SPECIAL_ITEM_EFFECT_TEXT = {
    "phantom_step": "8 seconds of delayed ghost dodge after lane change.",
    "afterimage_dash": "Two quick extra lane shifts are available in sequence.",
    "crowd_jammer": "Nearby hazard spawn pressure is reduced for a short time.",
    "impact_foam": "One collision becomes a stumble instead of a full crash.",
    "overclock_key": "Collected run keys can duplicate by +1 at run end.",
    "magnet_echo": "A weaker magnet pull lingers for 3 seconds after magnet ends.",
    "quiet_jet": "2 seconds of collision buffer after jetpack landing.",
    "combo_battery": "Coin streak keeps a short grace window before reset.",
    "hyper_sneakers": "Roll transition penalty is reduced during sneakers.",
    "risk_converter": "Near misses grant small Event Coin rewards.",
    "jackpot_fuse": "Mystery and Super box high-tier drop chance ramps up.",
    "chain_saver": "One power-up chain break is prevented per run.",
    "vault_seal": "A portion of banked coin loss is prevented when loss effects trigger.",
    "season_imprint": "Weekly passive bonus rotates with the active season imprint.",
}
SEASON_IMPRINT_TEXT = {
    "coin_drift": "Coin rewards are slightly increased.",
    "risk_bloom": "Near-miss rewards are stronger.",
    "safe_stride": "Run safety effects last a little longer.",
    "power_echo": "Temporary power-up durations are slightly extended.",
    "fortune_line": "Box jackpots are slightly more likely.",
    "streak_guard": "Coin streak grace lasts longer.",
    "spawn_calm": "Hazard pressure reduction is slightly stronger.",
}
SPECIAL_ITEM_ORDER = tuple(SPECIAL_ITEM_LABELS.keys())


@dataclass(frozen=True)
class LearnSoundEntry:
    key: str
    label: str
    description: str
    loop: bool = False
    gain: float = 1.0


@dataclass(frozen=True)
class HelpTopic:
    key: str
    label: str
    description: str


LEARN_SOUND_DETAILS: dict[str, LearnSoundEntry] = {
    "coin": LearnSoundEntry("coin", "Coin Pickup", "Plays when you collect a coin on the track."),
    "coin_gui": LearnSoundEntry("coin_gui", "Coin Bank", "Plays when coins are added to your saved total."),
    "jump": LearnSoundEntry("jump", "Jump", "Plays when you perform a normal jump."),
    "roll": LearnSoundEntry("roll", "Roll", "Plays when you duck under a high obstacle."),
    "dodge": LearnSoundEntry("dodge", "Lane Change", "Plays when you move left or right between lanes."),
    "announcer_jump_now": LearnSoundEntry("announcer_jump_now", "Announcer Jump Now", "Voice callout that tells you to jump immediately."),
    "announcer_roll_now": LearnSoundEntry("announcer_roll_now", "Announcer Roll Now", "Voice callout that tells you to roll immediately."),
    "announcer_move_left_now": LearnSoundEntry("announcer_move_left_now", "Announcer Move Left Now", "Voice callout that tells you to move left immediately."),
    "announcer_move_right_now": LearnSoundEntry("announcer_move_right_now", "Announcer Move Right Now", "Voice callout that tells you to move right immediately."),
    "landing": LearnSoundEntry("landing", "Landing", "Plays when you land after a normal jump."),
    "stumble": LearnSoundEntry("stumble", "Stumble", "Plays after a standard hit that still leaves one chance."),
    "stumble_side": LearnSoundEntry("stumble_side", "Side Stumble", "Plays after a side impact warning stumble."),
    "stumble_bush": LearnSoundEntry("stumble_bush", "Bush Stumble", "Plays when you hit a bush and survive the impact."),
    "crash": LearnSoundEntry("crash", "Crash", "Plays when a hoverboard absorbs a crash."),
    "death": LearnSoundEntry("death", "Death", "Main run over sound after the final hit."),
    "death_bodyfall": LearnSoundEntry("death_bodyfall", "Body Fall", "Body impact layer used during a full run loss."),
    "death_hitcam": LearnSoundEntry("death_hitcam", "Hit Camera", "Heavy hit layer used during the run over sequence."),
    "guard_catch": LearnSoundEntry("guard_catch", "Guard Catch", "Plays when the guard reaches you after a serious collision."),
    "guard_loop": LearnSoundEntry("guard_loop", "Guard Loop", "Short guard pressure loop after the first stumble.", loop=True, gain=0.72),
    "powerup": LearnSoundEntry("powerup", "Power Up", "Plays when you collect or activate a positive power item."),
    "powerdown": LearnSoundEntry("powerdown", "Power Down", "Plays when a temporary power effect expires."),
    "magnet_loop": LearnSoundEntry("magnet_loop", "Magnet Loop", "Looping sound while the coin magnet is active.", loop=True, gain=0.88),
    "jetpack_loop": LearnSoundEntry("jetpack_loop", "Jetpack Loop", "Looping sound while the jetpack is active.", loop=True, gain=0.88),
    "mystery_box": LearnSoundEntry("mystery_box", "Mystery Box", "Plays when a mystery box is collected or opened."),
    "mission_reward": LearnSoundEntry("mission_reward", "Mission Reward", "Reward chime for milestones, missions, and progress."),
    "train_pass": LearnSoundEntry("train_pass", "Train Pass", "Warning fly-by for a train moving through the scene."),
    "intro_start": LearnSoundEntry("intro_start", "Run Start", "Opening sound when a new run begins."),
    "intro_shake": LearnSoundEntry("intro_shake", "Headstart Shake", "Headstart launch shake effect."),
    "intro_spray": LearnSoundEntry("intro_spray", "Headstart Spray", "Headstart spray layer during the run intro."),
    "gui_cash": LearnSoundEntry("gui_cash", "Cash Reward", "Reward sound for large coin payouts."),
    "gui_close": LearnSoundEntry("gui_close", "Close Burst", "Sharp UI burst used before the revive choice."),
    "gui_tap": LearnSoundEntry("gui_tap", "Shop Tap", "Plays when a shop purchase is accepted."),
    "unlock": LearnSoundEntry("unlock", "Unlock", "Reward unlock sound for items and keys."),
    "left_foot": LearnSoundEntry("left_foot", "Left Footstep", "Regular left foot running step."),
    "right_foot": LearnSoundEntry("right_foot", "Right Footstep", "Regular right foot running step."),
    "sneakers_jump": LearnSoundEntry("sneakers_jump", "Super Sneakers Jump", "High jump launch used by super sneakers and pogo."),
    "sneakers_left": LearnSoundEntry("sneakers_left", "Super Sneakers Left Step", "Enhanced left footstep while super sneakers are active."),
    "sneakers_right": LearnSoundEntry("sneakers_right", "Super Sneakers Right Step", "Enhanced right footstep while super sneakers are active."),
    "slide_letters": LearnSoundEntry("slide_letters", "Letter Slide", "Plays when word hunt letters or intro tiles slide in."),
    "mystery_combo": LearnSoundEntry("mystery_combo", "Mystery Combo", "Bonus layer used for special mystery rewards."),
    "kick": LearnSoundEntry("kick", "Kick", "Impact layer used in the run over sequence."),
    "land_h": LearnSoundEntry("land_h", "Heavy Landing", "Heavy landing used after strong jumps or headstart endings."),
    "swish_short": LearnSoundEntry("swish_short", "Short Near Miss", "Short near-miss pass sound for a very quick close call."),
    "swish_mid": LearnSoundEntry("swish_mid", "Medium Near Miss", "Medium near-miss pass sound for a close call."),
    "swish_long": LearnSoundEntry("swish_long", "Long Near Miss", "Long near-miss pass sound for a sweeping close call."),
}
ACTIVE_GAMEPLAY_SOUND_KEYS: tuple[str, ...] = tuple(LEARN_SOUND_DETAILS.keys())
LEARN_SOUND_LIBRARY: tuple[LearnSoundEntry, ...] = tuple(LEARN_SOUND_DETAILS[key] for key in ACTIVE_GAMEPLAY_SOUND_KEYS)
HOW_TO_TOPICS: tuple[HelpTopic, ...] = (
    HelpTopic("movement", "Movement and Actions", "Move left and right to change lanes. Jump over low barriers and bushes. Roll under high barriers. Press Space to activate your selected hoverboard. Open Start Game to review your active board, headstarts, and score boosters before a run."),
    HelpTopic("warnings", "Hazards and Warnings", "Listen for the announcer callouts and the train fly-by sound. The callout focuses on the action needed for your current lane, such as jump, roll, move left, or move right. Near misses, collisions, hoverboard breaks, and guard pressure all have distinct audio layers."),
    HelpTopic("powerups", "Power Ups and Boards", "Collect magnets, jetpacks, double score, super sneakers, and pogo sticks to survive longer and build bigger scores. Your selected board also changes hoverboard behavior. Different boards can add double jump, super jump, super speed, smooth drift, sideways zaps, or longer low rolls."),
    HelpTopic("events", "Events and Daily Rewards", "Open Events from the main menu to review the current daily event, Daily High Score, Coin Meter, the mini mystery box daily gift, and the Daily Login Calendar. Daily events rotate through Super Mysterizer, Mega Jackpot, featured character bonuses, Super Mystery Box Mania, and Wordy Weekend."),
    HelpTopic("quests", "Missions and Quests", "Open Missions from the main menu to review mission sets, quests, and achievements. Mission sets raise your permanent multiplier. Daily and seasonal quests award sneakers, and sneakers fill the quest meter for extra rewards. Word Hunt letters and Season Hunt tokens still appear during runs and remain part of progression."),
    HelpTopic("collections", "Boards and Collections", "Open Me from the main menu to manage characters, boards, item upgrades, and collections. Collections complete when you unlock specific character or board sets. Finished collections grant passive bonuses such as stronger coin banking, longer hoverboards, longer power-up duration, or a higher starting multiplier."),
    HelpTopic("economy", "Coins, Keys, and Shop", "Collect coins during runs and bank them when the run ends. Keys can revive you after a crash. Spend saved coins in Shop on hoverboards, headstarts, score boosters, mystery boxes, and upgrades. Shop also includes the free daily gift when it is available."),
    HelpTopic("leaderboard", "Leaderboard and Publishing", "Open Leaderboard from the main menu after signing in through Options. The board tracks the current weekly season, shows the remaining time and active reward, lets you filter by difficulty, inspect player profiles, and publish finished runs with extended run details and verification status."),
    HelpTopic("navigation", "Menu Navigation", "The main menu is organized into Start Game, Events, Missions, Me, Shop, Leaderboard, Options, How to Play, Learn Game Sounds, Check for Updates, and Exit. Use Up and Down to move, Enter to confirm, Escape to go back, and Left or Right when adjusting options."),
)
UPGRADE_HELP_TOPICS: dict[str, tuple[HelpTopic, ...]] = {
    "1.1.3": (
        HelpTopic("update_1_1_3_audio", "Audio Routing Fixes", "Version 1.1.3 keeps reward and interface sounds out of the forced HRTF mono path while preserving mono menu feedback cues."),
        HelpTopic("update_1_1_3_items", "Item Upgrades", "The Shop now includes an original-style Item Upgrades submenu for Coin Magnet, Jetpack, 2X Multiplier, and Super Sneakers, each with persistent upgrade levels and longer pickup durations."),
    ),
}
TEXT = {
    "unknown": "Unknown",
    "whats_new_title": "What's New",
    "whats_new_fallback": "No update notes were provided for this version.",
    "back": "Back",
    "yes": "Yes",
    "no": "No",
}


_STRING_BANK: tuple[str, ...] = (
    'main',
    'audio_output_device',
    '',
    '{0} {1}',
    ' ',
    'System Default',
    'Unavailable',
    'Default Voice',
    'left_foot',
    'sneakers_left',
    'right_foot',
    'sneakers_right',
    'jump',
    'sneakers_jump',
    'roll',
    'dodge',
    'landing',
    'land_h',
    'coin',
    'powerup',
    'powerdown',
    'mystery_box',
    'stumble',
    'stumble_side',
    'stumble_bush',
    'crash',
    'death',
    'kick',
    'guard_catch',
    'player_jump',
    'player_roll',
    'player_dodge',
    'player_land',
    'player_pickup',
    'player_power',
    'player_powerdown',
    'player_box',
    'player_impact',
    'player_crash',
    'player_death',
    'player_guard',
    'player_kick',
    'move',
    'act',
    'act2',
    'headstart_end',
    'headstart_reward',
    'player_move',
    'player_action',
    'player_reward',
    'player_footstep',
    'menumove',
    'menuedge',
    'menuwrap',
    'menuopen',
    'menuclose',
    'confirm',
    'binding_countdown',
    'binding_done',
    'binding_fail',
    'announcer_jump_now',
    'announcer_move_left_now',
    'announcer_move_right_now',
    'announcer_roll_now',
    'jump_now.mp3',
    'move_left_now.mp3',
    'move_right_now.mp3',
    'roll_now.mp3',
    '.ogg',
    '.wav',
    '.mp3',
    'menu',
    'gameplay',
    'Speaker',
    'menu_intro',
    'game_intro',
    'menu_theme',
    'gameplay_main',
    'subway_surfers_theme',
    'main_theme',
    'theme',
    'run_theme',
    '{0}__{1}',
    'fade_in',
    'fade_out',
    'nt',
    'outputs',
    'assets',
    '{0}.wav',
    'sfx',
    'coin_gui',
    'death_bodyfall',
    'death_hitcam',
    'guard_loop',
    'magnet_loop',
    'jetpack_loop',
    'connect',
    'high',
    'mystery_box_open',
    'wheel_spin',
    'mission_reward',
    'train_pass',
    'intro_start',
    'intro_shake',
    'intro_spray',
    'gui_cash',
    'gui_close',
    'gui_tap',
    'unlock',
    'slide_letters',
    'mystery_combo',
    'swish_short',
    'swish_mid',
    'swish_long',
    'sfx_{0}',
    '_channel_polyphony_index',
    '__',
    'speech_enabled',
    'sapi_speech_enabled',
    'sapi_voice_id',
    'sapi_rate',
    'sapi_pitch',
    'sapi_volume',
    'SAPI.SpVoice',
    'Voice',
    '<pitch middle="{0:+d}">{1}</pitch>',
    'has_rate',
    'set_rate',
    'min_rate',
    'max_rate',
    'sfx_volume',
    '{0}{1}',
    'announcer',
    'coin.wav',
    'coin_gui.wav',
    'jump.wav',
    'roll.wav',
    'dodge.wav',
    'landing.wav',
    'stumble.wav',
    'crash.wav',
    'death.wav',
    'death_bodyfall.wav',
    'death_hitcam.wav',
    'guard_catch.wav',
    'guard_loop.wav',
    'powerup.wav',
    'powerdown.wav',
    'magnet_loop.wav',
    'jetpack_loop.wav',
    'mystery_box.wav',
    'Hr_mysteryBoxOpen #20822.wav',
    'wheel_spin.mp3',
    'mission_reward.wav',
    'train_pass.wav',
    'intro_start.wav',
    'intro_shake.wav',
    'intro_spray.wav',
    'Hr_gui_cash #00120.wav',
    'gui_close.wav',
    'gui_tap.wav',
    'unlock.wav',
    'left_foot.wav',
    'right_foot.wav',
    'sneakers_jump.wav',
    'sneakers_left.wav',
    'sneakers_right.wav',
    'slide_letters.wav',
    'mystery_combo.wav',
    'stumble_side.wav',
    'stumble_bush.wav',
    'kick.wav',
    'land_h.wav',
    'swish_short.wav',
    'swish_mid.wav',
    'swish_long.wav',
    'binding_countdown.wav',
    'binding_done.wav',
    'binding_fail.wav',
    'sfx_',
    'ui',
    'intro',
    'boost',
    '_music_ducking_level',
    '_music_ducking_target',
    'Id',
    '<pitch middle="',
    '">',
    '</pitch>',
    'rb',
    'foot',
    'warning',
    'music',
    '+d',
    'loop_guard',
    'menu_sound_hrtf',
    'music_volume',
    'loop_jetpack',
    'loop_magnet',
    'easy',
    'normal',
    'hard',
    'board_progress',
    'selected_board',
    'classic',
    'Classic',
    'standard',
    'Standard Shield',
    'The baseline hoverboard with pure protection and no extra modifier.',
    'bouncer',
    'Bouncer',
    'double_jump',
    'Double Jump',
    'Lets you jump once more while riding the board.',
    'monster',
    'Monster',
    'super_jump',
    'Super Jump',
    'Launches into a stronger jump arc while the board is active.',
    'sharpeed',
    'Sharpeed',
    'super_speed',
    'Super Speed',
    'Adds extra forward speed while surfing on the board.',
    'drift_king',
    'Drift King',
    'smooth_drift',
    'Smooth Drift',
    'Extends air hang time and makes movement feel glider-light.',
    'zapper',
    'Zapper',
    'zap_sideways',
    'Zap Sideways',
    'Lets lane changes snap across two lanes while the board is active.',
    'low_rider',
    'Low Rider',
    'stay_low',
    'Stay Low',
    'Keeps rolls active longer and lowers your profile under obstacles.',
    'unlocked',
    'character_progress',
    'selected_character',
    'coin_bank_pct',
    'Coin banking +{0}%',
    'hoverboard_duration_sec',
    'Hoverboard shield +{0}s',
    'power_duration_pct',
    'Power duration +{0}%',
    'starting_multiplier',
    'Start multiplier +{0}',
    'jake',
    'Jake',
    'Banks extra coins at the end of a run.',
    'tricky',
    'Tricky',
    'Extends the hoverboard shield when you activate one.',
    'fresh',
    'Fresh',
    'Extends temporary power-up duration.',
    'yutani',
    'Yutani',
    'Starts each run with a higher score multiplier.',
    'spike',
    'Spike',
    'Banks even more coins at the end of a run.',
    'dino',
    'Dino',
    'Extends hoverboard protection longer than anyone else.',
    'lucy',
    'Lucy',
    'Improves end-of-run coin banking with precision thief timing.',
    'prince_k',
    'Prince K',
    'Starts runs with a royal score multiplier lead.',
    'brody',
    'Brody',
    'Extends active power-up uptime with surfer-level focus.',
    'tasha',
    'Tasha',
    'Keeps hoverboard shields active longer in clutch sections.',
    'ella',
    'Ella',
    'Stretches temporary power-up windows for longer control.',
    'ninja',
    'Ninja',
    'Opens each run with a stealth multiplier advantage.',
    'boombot',
    'Boombot',
    'Extends temporary power-up duration with a premium robotics edge.',
    'level',
    'Coin banking +',
    '%',
    '.',
    'Hoverboard shield +',
    's',
    'Power duration +',
    'Start multiplier +',
    '0',
    '{0:.1f}',
    '.1f',
    'collections_completed',
    'street_crew',
    'Street Crew',
    'Unlock Jake, Tricky, and Fresh to gain a stronger opening multiplier.',
    'future_set',
    'Future Set',
    'Unlock Yutani, Dino, and Boombot for stronger end-of-run coin banking.',
    'board_boosters',
    'Board Boosters',
    'Collect Classic, Bouncer, Monster, and Sharpeed for a longer shield ride.',
    'style_masters',
    'Style Masters',
    'Collect Drift King, Zapper, and Low Rider to extend temporary power-ups.',
    'Vireon Interactive',
    'SubwaySurfersBlind',
    'menu_wrap_enabled',
    'check_updates_on_startup',
    'last_seen_version',
    'difficulty',
    'announce_lane',
    'announce_coins_every',
    'meter_announcements_enabled',
    'coin_counters_enabled',
    'quest_changes_enabled',
    'pause_on_focus_loss_enabled',
    'practice_speed_scaling_enabled',
    'practice_hazard_target',
    'main_menu_descriptions_enabled',
    'confirm_exit_enabled',
    'confirm_purchase_enabled',
    'leaderboard_username',
    'leaderboard_session_token',
    'leaderboard_applied_reward_ids',
    'bank_coins',
    'keys',
    'hoverboards',
    'headstarts',
    'score_boosters',
    'item_upgrades',
    'mission_set',
    'mission_multiplier_bonus',
    'mission_metrics',
    'word_hunt_day',
    'word_hunt_letters',
    'word_hunt_streak',
    'word_hunt_completed_on',
    'season_hunt_id',
    'season_tokens',
    'season_reward_stage',
    'achievement_progress',
    'achievements_unlocked',
    'quest_state',
    'event_state',
    'word_hunt_active_word',
    'keyboard_bindings',
    'controller_bindings',
    'keyboard_layout_signature',
    'keyboard_layout_locale',
    'keyboard_layout_locale_label',
    'keyboard_layout_code',
    'keyboard_layout_name',
    '_MEIPASS',
    'frozen',
    'coins',
    'jumps',
    'rolls',
    'dodges',
    'powerups',
    'boxes',
    'total_coins_collected',
    'total_jumps',
    'total_rolls',
    'total_dodges',
    'total_boxes_opened',
    'best_distance',
    'best_word_hunt_streak',
    'total_season_tokens',
    'data',
    'settings.json',
    'settings.json.bak',
    'APPDATA',
    'Roaming',
    'w',
    'AppData',
    'LOCALAPPDATA',
    'r',
    'utf-8',
    'Local',
    'game',
    'xbox',
    'playstation',
    'generic',
    'Unassigned',
    '00000409',
    '00000809',
    '00000407',
    '0000040C',
    '00000410',
    '0000040A',
    '0000041F',
    '0001041F',
    '00000419',
    'US QWERTY',
    'UK QWERTY',
    'German QWERTZ',
    'French AZERTY',
    'Italian QWERTY',
    'Spanish QWERTY',
    'Turkish Q',
    'Turkish F',
    'Russian JCUKEN',
    'tr',
    'en',
    'de',
    'fr',
    'es',
    'it',
    'ru',
    'Turkish',
    'English',
    'German',
    'French',
    'Spanish',
    'Italian',
    'Russian',
    'a',
    'b',
    'x',
    'y',
    'back',
    'start',
    'guide',
    'leftshoulder',
    'rightshoulder',
    'leftstick',
    'rightstick',
    'dpad_up',
    'dpad_down',
    'dpad_left',
    'dpad_right',
    'leftx',
    'lefty',
    'rightx',
    'righty',
    'triggerleft',
    'triggerright',
    'Up Arrow',
    'Down Arrow',
    'Left Arrow',
    'Right Arrow',
    'Enter',
    'Numpad Enter',
    'Escape',
    'Space',
    'Home',
    'End',
    'Page Up',
    'Page Down',
    'Delete',
    'A',
    'B',
    'X',
    'Y',
    'View',
    'Menu',
    'Xbox Button',
    'LB',
    'RB',
    'Left Stick Press',
    'Right Stick Press',
    'D-Pad Up',
    'D-Pad Down',
    'D-Pad Left',
    'D-Pad Right',
    'Cross',
    'Circle',
    'Square',
    'Triangle',
    'Create',
    'Options',
    'PS Button',
    'L1',
    'R1',
    'L3',
    'R3',
    'South Button',
    'East Button',
    'West Button',
    'North Button',
    'Back',
    'Start',
    'Guide',
    'Left Shoulder',
    'Right Shoulder',
    'leftx:-1',
    'leftx:1',
    'lefty:-1',
    'lefty:1',
    'rightx:-1',
    'rightx:1',
    'righty:-1',
    'righty:1',
    'triggerleft:1',
    'triggerright:1',
    'Left Stick Left',
    'Left Stick Right',
    'Left Stick Up',
    'Left Stick Down',
    'Right Stick Left',
    'Right Stick Right',
    'Right Stick Up',
    'Right Stick Down',
    'Left Trigger',
    'Right Trigger',
    'Standard Keyboard',
    '{0}|{1}|{2}',
    'Generic Controller',
    'menu_up',
    'Menu Up',
    'button:dpad_up',
    'menu_down',
    'Menu Down',
    'button:dpad_down',
    'menu_confirm',
    'Confirm',
    'button:a',
    'menu_back',
    'button:b',
    'option_decrease',
    'Option Decrease',
    'button:dpad_left',
    'option_increase',
    'Option Increase',
    'button:dpad_right',
    'game_move_left',
    'Move Left',
    'axis:leftx:-1',
    'game_move_right',
    'Move Right',
    'axis:leftx:1',
    'game_jump',
    'Jump',
    'game_roll',
    'Roll',
    'game_hoverboard',
    'Activate Hoverboard',
    'button:x',
    'game_pause',
    'Pause',
    'button:start',
    'game_toggle_speech',
    'Toggle Speech',
    'button:y',
    '_',
    '-',
    'Unknown Locale',
    '|',
    'Xbox Controller',
    'PlayStation Controller',
    'Key {0}',
    ':',
    'button',
    'axis',
    'keyboard',
    '{0}: {1}',
    'controller',
    'button:{0}',
    'axis:{0}:{1}',
    'user32',
    'key',
    'modifiers',
    'label',
    'Key ',
    'Keyboard',
    'No controller connected',
    ': ',
    'button:',
    'axis:',
    'unknown',
    'default',
    'Ctrl',
    'Alt',
    'Shift',
    'Meta',
    ' + ',
    '@',
    'xinput',
    'dualshock',
    'dualsense',
    'wireless controller',
    'ps4',
    'ps5',
    'kind',
    'amount',
    'hoverboard',
    'headstart',
    'score_booster',
    'event_coins',
    'super_box',
    'daily_high_score_day',
    'daily_high_score_total',
    'daily_high_score_claimed_tiers',
    'coin_meter_day',
    'coin_meter_coins',
    'coin_meter_claimed_tiers',
    'daily_gift_claimed_on',
    'login_calendar_cycle_start',
    'login_calendar_claimed_days',
    'login_calendar_last_claimed_on',
    'wordy_weekend',
    'event',
    'featured_character_key',
    'featured_character_active',
    'featured_multiplier_bonus',
    'super_box_bonus',
    'word_bonus',
    'box_bonus',
    'jackpot_bonus',
    'super_mysterizer',
    'Super Mysterizer',
    'Monday boosts Super Mystery Box appearances during runs.',
    'mega_jackpot',
    'Mega Jackpot',
    'Tuesday improves Mystery Box rewards with jackpot-heavy luck.',
    'featured_character_bonus',
    'Character Bonus',
    'Wednesday grants a bonus multiplier if you run with the featured character.',
    'Thursday grants a bonus multiplier if you run with the featured character.',
    'super_mystery_box_mania',
    'Super Mystery Box Mania',
    'Friday places extra Super Mystery Boxes directly on the track.',
    'Wordy Weekend',
    'Weekend Word Hunt uses your selected character and spawns more letters.',
    'magnet',
    'mult2x',
    'sneakers',
    'hover',
    'mult',
    'nothing',
    'jackpot',
    'learn_sound_preview',
    'intro_headstart_shake',
    'intro_headstart_spray',
    'train',
    'low',
    'bush',
    '{0}s',
    '{0:02d}:{1:02d}',
    '{0:02d}:{1:02d}:{2:02d}',
    'movement',
    'Controls: {0} {1}',
    '\r',
    '\n',
    'windll',
    'scrap',
    'Press Enter to play the selected game sound.',
    'Check GitHub Releases for a newer version.',
    'No release notes were provided.',
    'idle',
    'season',
    'all',
    'Run ended.',
    'SFX Volume: {0}',
    'Main Menu   Version: {0}',
    'Achievements   {0}/{1}',
    'Shop',
    'Coins: {0}',
    'Music Volume: {0}',
    'Check for Updates on Startup: {0}',
    'Speech: {0}',
    'SAPI Speech: {0}',
    'SAPI Settings',
    'Output Device: {0}',
    'Menu Sound HRTF: {0}',
    'Menu Wrap: {0}',
    'SAPI Voice: {0}',
    'SAPI Rate: {0}',
    'SAPI Pitch: {0}',
    'SAPI Volume: {0}',
    'Difficulty: {0}',
    'Meters: {0}',
    'Coin Counters: {0}',
    'Quest Announcements: {0}',
    'Pause on Focus Loss: {0}',
    'Main Menu Descriptions: {0}',
    'Set User Name',
    'Log Out',
    'Exit Confirmation: {0}',
    'Purchase Confirmation: {0}',
    'Headstart: {0}   Owned: {1}',
    'Score Booster: {0}   Owned: {1}',
    'Use {0} key{1} to revive   Owned: {2}',
    'Buy Hoverboard   Cost: {0} Coins   Owned: {1}   Max Buy: {2}',
    'Open Mystery Box   Cost: {0} Coins   Max Buy: {1}',
    'Buy Headstart   Cost: {0} Coins   Owned: {1}   Max Buy: {2}',
    'Buy Score Booster   Cost: {0} Coins   Owned: {1}   Max Buy: {2}',
    'Item Upgrades   Maxed: {0}/{1}',
    'Character Upgrades   Active: {0}',
    'Board: {0}   Power: {1}',
    '{0}: {1}   Owned: {2}',
    'Weekly Spins: {0}/{1} remaining',
    'Season Imprint: {0}   {1}',
    'Spin Wheel',
    'Wheel Spin',
    'Practice Speed Scaling: {0}',
    'Practice Hazard Target: {0}',
    'Events   {0}   Event Coins: {1}',
    'Event Shop   Event Coins: {0}',
    'Season Character: {0}   {1}',
    'Season Board: {0}   {1}',
    'Buy Key   Cost: {0} Event Coins   Owned: {1}',
    'Buy Hoverboard Pack (2)   Cost: {0} Event Coins   Owned: {1}',
    'Buy Headstart   Cost: {0} Event Coins   Owned: {1}',
    'Buy Score Booster   Cost: {0} Event Coins   Owned: {1}',
    'Open Super Mystery Box   Cost: {0} Event Coins',
    'Today: {0}   Tomorrow: {1}',
    'Daily High Score: {0} of {1}',
    'Next Daily High Score Reward at {0}',
    'Coin Meter: {0} of {1}',
    'Next Coin Meter Chest at {0}',
    'Daily Login Calendar: Day {0} of 7   {1}',
    'Login Reward Claimed Today',
    'Word Hunt: {0}   {1}/{2} letters',
    'Season Hunt: {0} of {1} tokens',
    'Missions   Set {0}   {1}/3',
    'Mission Set {0}',
    'Me   {0}   {1}',
    'Boards   Active: {0}',
    '{0}   {1}   {2}',
    'Status: {0}',
    'Power: {0}   {1}',
    'Set as Active Board',
    'Collections   {0}/{1}',
    '{0}   {1}   {2}/{3}   {4}',
    'Quests   Sneakers: {0}',
    '{0}: {1}   {2}/{3}   {4}   Sneakers {5}',
    'Sneaker Meter: {0} of {1}',
    'Next Sneaker Meter Reward at {0}',
    '{0}   {1}/{2}   {3}',
    "Reset Today's Progress   Keeps claimed rewards",
    '{0}   Level {1}/{2}   {3}',
    'Status: Level {0} of {1}',
    'Effect: {0} Current {1}   Next {2}',
    'Upgrade to Level {0}   Cost: {1} Coins',
    '{0}   {1}   Level {2}/{3}   {4}',
    'Status: {0}   Level {1} of {2}',
    'Perk: {0}',
    'Set as Active Character',
    'Score: {0}',
    'Play Time: {0}',
    'Death reason: {0}',
    'Run again',
    'Main menu',
    '{0} copied to clipboard.',
    'Controls',
    '{0} Bindings',
    'Open Release Page',
    'open_release_page',
    'Use {0}/{1}, {2} to select, {3} to go back.',
    'Adjust values with {0}/{1}.',
    'Use {0} and {1} to change lanes. Press {2} to jump, {3} to roll, {4} to activate a hoverboard, {5} to pause, and {6} to toggle speech. On keyboard, press R to hear coins and T to hear play time.',
    'download',
    'Starting update download.',
    'Installing Update...',
    'install_busy',
    'Restart Game',
    'restart_after_update',
    'Quit Game',
    'quit',
    'ready',
    'Missions {0}/3',
    '{0} day{1} {2} hour{3} {4} minute{5}',
    'Season Ends In: {0}',
    'Season Reward: {0}. {1}',
    'Season: Loading current week',
    'Season Leaderboard   {0}/{1}',
    'Season: {0}',
    'Published Run',
    'Page {0} of {1}',
    '{0}: {1}: {2}: {3}',
    'Title: {0}',
    'Message: {0}   {1}/{2} chars   {3} lines',
    'Report a Bug   {0}/{1}',
    'Report a Bug   Compose',
    'publishing',
    '02d',
    'verified',
    'Controls: ',
    '{0}   {1}',
    'CHANGELOG.txt',
    '------------------------------------------------------------',
    'win32',
    'segoeui',
    'learn_sound:{0}',
    'Paused',
    'Return to Main Menu?',
    'Log Out of Leaderboard?',
    'Return to Desktop?',
    'Revive',
    'Publish to Leaderboard?',
    'Confirm Purchase?',
    'Game Over',
    'Run Setup',
    'Events',
    'Event Shop',
    'Missions',
    'Mission Set',
    'Quests',
    'Me',
    'Gameplay Announcements',
    'Server',
    'Leaderboard',
    'Player',
    'Report a Bug',
    'Bug Report',
    'Keyboard Bindings',
    'Controller Bindings',
    'Learn Game Sounds',
    'How to Play',
    'Help',
    "What's New",
    'Update Required',
    'SFX Volume: ',
    'Main Menu   Version: ',
    'Achievements   ',
    '/',
    'Updated Help   {0}',
    'Coins: ',
    'Music Volume: ',
    'Check for Updates on Startup: ',
    'Speech: ',
    'SAPI Speech: ',
    'Output Device: ',
    'Menu Sound HRTF: ',
    'Menu Wrap: ',
    'SAPI Voice: ',
    'SAPI Rate: ',
    'SAPI Pitch: ',
    'SAPI Volume: ',
    'Normal',
    'Difficulty: ',
    'Meters: ',
    'Coin Counters: ',
    'Quest Announcements: ',
    'Pause on Focus Loss: ',
    'Main Menu Descriptions: ',
    'Set User Name: {0}',
    'Log Out: {0}',
    'Exit Confirmation: ',
    'Purchase Confirmation: ',
    'Headstart: ',
    '   Owned: ',
    'Score Booster: ',
    'Revive unavailable   Limit reached: {0} per run',
    'Use ',
    ' key',
    ' to revive   Owned: ',
    'Buy Hoverboard   Cost: ',
    ' Coins   Owned: ',
    '   Max Buy: ',
    'Open Mystery Box   Cost: ',
    ' Coins   Max Buy: ',
    'Buy Headstart   Cost: ',
    'Buy Score Booster   Cost: ',
    'Item Upgrades   Maxed: ',
    'Character Upgrades   Active: ',
    'Free Daily Gift   Available',
    'Free Daily Gift   Claimed Today',
    'Board: ',
    '   Power: ',
    'Practice Setup',
    'Special Item',
    'Weekly Spins: ',
    ' remaining',
    'Season Imprint: Syncing...',
    'Weekly bonus is active.',
    'Season Imprint: ',
    '   ',
    'Spin Wheel   Sign in required',
    'Spin Wheel   No spins left this week',
    'Practice Speed Scaling: ',
    'Practice Hazard Target: ',
    'Events   ',
    '   Event Coins: ',
    'Event Shop   Event Coins: ',
    'Season Character   All unlocked',
    'Owned',
    'Cost: {0} Event Coins',
    'Season Character: ',
    'Season Board   All unlocked',
    'Season Board: ',
    'Buy Key   Cost: ',
    ' Event Coins   Owned: ',
    'Buy Hoverboard Pack (2)   Cost: ',
    'Open Super Mystery Box   Cost: ',
    ' Event Coins',
    'Today: {0}   Featured Runner: {1}   Tomorrow: {2}',
    'Today: ',
    '   Tomorrow: ',
    'Daily High Score: {0}   All rewards claimed',
    'Daily High Score: ',
    ' of ',
    'Claim Daily High Score Reward',
    'Daily High Score Rewards Complete',
    'Next Daily High Score Reward at ',
    'Coin Meter: {0}   All chests opened',
    'Coin Meter: ',
    'Open Coin Meter Chest',
    'Coin Meter Complete',
    'Next Coin Meter Chest at ',
    'Available',
    'Already claimed today',
    'Daily Login Calendar: Day ',
    ' of 7   ',
    'Claim Login Reward   Day {0}',
    'Word Hunt: ',
    ' letters',
    'Season Hunt: {0} tokens   Track complete',
    'Season Hunt: ',
    ' tokens',
    'Missions   Set ',
    '/3',
    'Mission Set ',
    'Me   ',
    'Boards   Active: ',
    '{0}   Locked   Unlock: {1} Coins',
    'Active',
    'Unlocked',
    'Status: Locked   Unlock cost: {0} Coins',
    'Status: ',
    'Power: ',
    'Unlock Board   Cost: {0} Coins',
    'Board Active',
    'Collections   ',
    'Complete',
    'In Progress',
    'Quests   Sneakers: ',
    'Claimed',
    'Daily',
    'Seasonal',
    '   Sneakers ',
    'Sneaker Meter: {0}   Complete',
    'Sneaker Meter: ',
    'Claim Sneaker Meter Reward',
    'Sneaker Meter Complete',
    'Next Sneaker Meter Reward at ',
    'Completed',
    '   Level ',
    'Status: Level ',
    'Effect: {0} Pickup duration {1}',
    'Effect: ',
    ' Current ',
    '   Next ',
    'Max Level Reached',
    'Upgrade to Level ',
    '   Cost: ',
    ' Coins',
    'Perk: ',
    'Unlock Character   Cost: {0} Coins',
    'Character Active',
    'Unlock character first to upgrade',
    'Score: ',
    'Play Time: ',
    'Death reason: ',
    'game_over_retry',
    'game_over_main_menu',
    'clean_escapes',
    'powerup_usage',
    'score',
    'play_time_seconds',
    'death_reason',
    'game_version',
    'distance_meters',
    'revives_used',
    'Power-ups: none',
    'Power-ups: ',
    'item_upgrade_purchase:{0}',
    'item_upgrade_max_info:{0}',
    'character_unlock:{0}',
    'character_unlock_hint:{0}',
    'board_unlock:{0}',
    '{0} unlocked with Event Coins.',
    'Unable to copy text to the clipboard.',
    ' copied to clipboard.',
    'select_binding_profile',
    'Keyboard Bindings ({0})',
    ' Bindings',
    'Return to the main menu.',
    '{0}. {1}',
    'Unknown',
    'Update Required   {0} -> {1}',
    'A newer version is available. Current version {0}. Latest version {1}.',
    'Update Available   {0} -> {1}',
    'A newer release is available. This source checkout reports version {0}. Latest release {1}.',
    'Download and Install Update',
    'download_update',
    ', ',
    ' to select, ',
    ' to go back.',
    'Adjust values with ',
    ' and ',
    ' to change lanes. Press ',
    ' to jump, ',
    ' to roll, ',
    ' to activate a hoverboard, ',
    ' to pause, and ',
    ' to toggle speech. On keyboard, press R to hear coins and T to hear play time.',
    'error',
    'Current version {0}. Latest release {1}. {2}',
    'Run ended after crash',
    'Game Over.',
    'Missions ',
    'power',
    'box',
    'Mission set complete. Super Mystery Box.',
    "Today's progress was reset. Claimed rewards stayed claimed.",
    'jackpot_fuse',
    'jetpack',
    '{0}: Super Mystery Box. {1} coins saved.',
    'Word Hunt complete. Streak {0}. Super Mystery Box.',
    'Word Hunt',
    'Season Hunt reward. Super Mystery Box.',
    'Season Hunt',
    ' day',
    ' hour',
    ' minute',
    'Season Ends In: Loading...',
    'Season Ends In: ',
    'Season Reward: ',
    '. ',
    'Season: {0} ({1})',
    'Season reward for rank {0}',
    'special_items',
    'special_item_loadout',
    'wheel',
    'leaderboard_startup_sync',
    'Checking seasonal rewards...',
    'safe_stride',
    'special_item_consume_sync',
    'Wheel Loadout',
    'Syncing special item usage...',
    '{0} unlocked.',
    '{0} selected.',
    '{0} upgraded to level {1}. {2}.',
    '{0} upgraded to level {1}. Pickup duration {2}.',
    '{0} reward is unavailable.',
    'Opening Mystery Box.',
    'Mystery box: empty.',
    'runs_completed',
    'WINDOWFOCUSGAINED',
    'WINDOWFOCUSLOST',
    'WINDOWTAKEFOCUS',
    'WINDOWMINIMIZED',
    'WINDOWRESTORED',
    '{0} connected. Open Controls in Options to review bindings.',
    '{0} disconnected. Keyboard controls remain available.',
    'Press a button or stick direction on the {0} for {1}. Press Escape to cancel.',
    'Ctrl + {0}',
    'Alt + {0}',
    'Shift + {0}',
    'Meta + {0}',
    'Hold {0} for 3 seconds.',
    'Binding failed. Keep the selected keys pressed for the full 3 seconds.',
    '{0} set to {1}.',
    'coin_drift',
    'sync_payload',
    'Wheel reward: {0} {1}{2}.',
    'close',
    'leaderboard_profile',
    'leaderboard_auth',
    'leaderboard_publish',
    'published',
    'issue_detail',
    'issue_submit',
    'investigating',
    'wheel_sync',
    'special_item_toggle',
    'This server does not support the bug report system yet. Update the server and try again.',
    'Syncing wheel status...',
    'Spinning the wheel...',
    'Updating {0}...',
    'Season Leaderboard   ',
    'Season: ',
    'leaderboard_refresh',
    'Loading {0}...',
    'Unable to open the selected run.',
    'Connecting to server...',
    'Leaderboard account signed out.',
    'Page ',
    'Unknown user',
    'Title: Not set',
    '{0}...',
    'Title: ',
    'Message: Not set',
    'Blank lines only',
    'Message: ',
    ' chars   ',
    ' lines',
    'Report a Bug   ',
    'issue_connect',
    'issue_refresh',
    'issue_prev_page',
    'issue_next_page',
    'Loading bug report...',
    'Created: {0}',
    'Message:',
    'title',
    'Bug Report Title',
    'issue_edit_title',
    'issue_edit_message',
    'edit_practice_hazard_target',
    'Submitting bug report...',
    'Publishing your score...',
    'Requested output device unavailable. Using {0}.',
    'opt_sfx',
    'opt_music',
    'opt_updates',
    'opt_output',
    'opt_menu_hrtf',
    'opt_menu_wrap',
    'opt_speech',
    'opt_sapi',
    'opt_sapi_volume',
    'opt_sapi_voice',
    'opt_sapi_rate',
    'opt_sapi_pitch',
    'opt_diff',
    'opt_main_menu_descriptions',
    'opt_exit_confirmation',
    'opt_purchase_confirmation',
    'opt_meters',
    'opt_coin_counters',
    'opt_quest_changes',
    'opt_pause_on_focus_loss',
    'practice_runs_completed',
    'Practice Lane complete. Cleared {0} hazards.',
    'Practice complete. Hazards cleared: {0}.',
    'pogo_active',
    'word',
    'season_token',
    'multiplier',
    'pogo',
    '2x multiplier.',
    'Pogo stick.',
    'overclock_key',
    'Key collected. Total keys: {0}.',
    'Letter {0}. {1} letters left.',
    'Season token. {0} of {1}.',
    'You can revive for {0} key{1}.',
    'Revived. Temporary shield active.',
    'Run over. Score {0}. {1}.',
    'You crashed. One chance left.',
    'Multiplier: x{0}',
    'Speed: {0:.1f}',
    'Boards: {0}',
    'Keys: {0}',
    '   [Hoverboard]',
    '   [Headstart]',
    '   [Magnet]',
    '   [Jetpack]',
    '   [2x]',
    '   [Super Sneakers]',
    '   [Practice Lane {0}/{1}   Left: {2}]',
    '{0}   Word Hunt: {1} / {2}   Season Hunt: {3}',
    '(?<=[.!?])\\s+',
    'Date: ',
    '\r\n',
    'window',
    'learn_sound:',
    'Checking for updates.',
    'Updated Help   ',
    'Set User Name: ',
    'Log Out: ',
    'Revive unavailable   Limit reached: ',
    ' per run',
    'wheel_info',
    'wheel_spin_now',
    'loadout_board_info',
    'toggle_headstart',
    'toggle_score_booster',
    'Cost: ',
    '   Featured Runner: ',
    '   All rewards claimed',
    '   All chests opened',
    'Claim Login Reward   Day ',
    ' tokens   Track complete',
    '   Locked   Unlock: ',
    'Status: Locked   Unlock cost: ',
    'Unlock Board   Cost: ',
    'Ready',
    'daily',
    '   Complete',
    ' Pickup duration ',
    'Unlock Character   Cost: ',
    'opt_sapi_menu',
    'opt_leaderboard_account',
    'item_upgrade_purchase:',
    'item_upgrade_max_info:',
    'item_upgrade_status_info:{0}',
    'item_upgrade_effect_info:{0}',
    'character_unlock:',
    'character_active_info:{0}',
    'character_select:{0}',
    'character_unlock_hint:',
    'character_max_info:{0}',
    'character_upgrade:{0}',
    'character_status_info:{0}',
    'character_perk_info:{0}',
    'board_unlock:',
    'board_active_info:{0}',
    'board_select:{0}',
    'board_status_info:{0}',
    'board_power_info:{0}',
    'event_info',
    'Open Event Shop',
    'open_event_shop',
    'claim_daily_high_score',
    'claim_coin_meter',
    'Mini Mystery Box: {0}',
    'claim_daily_gift',
    'claim_login_reward',
    'event_shop_buy_character',
    'event_shop_buy_board',
    'event_shop_buy_key',
    'event_shop_buy_hoverboards',
    'event_shop_buy_headstart',
    'event_shop_buy_score_booster',
    'event_shop_buy_super_box',
    'Not enough Event Coins. {0} needed, {1} available.',
    'All season character offers are already unlocked.',
    '{0} is already unlocked.',
    'ui3',
    ' unlocked with Event Coins.',
    'All season board offers are already unlocked.',
    'open_quests',
    'open_mission_set',
    'open_achievements',
    'mission_info',
    'Permanent Multiplier: x{0}',
    'quest_info',
    'claim_quest_meter',
    'claim_quest:{0}',
    'reset_daily_progress',
    'open_characters',
    'open_boards',
    'open_item_upgrades',
    'open_collections',
    'Nothing available to copy.',
    '{0}/{1}',
    'Achievement unlocked: {0}.',
    'ui2',
    'Collection complete: {0}. {1}.',
    'Active Input: {0}',
    'announce_active_input',
    'Binding Profile: {0}',
    'Customize Bindings',
    'open_selected_bindings',
    'Reset {0}',
    'reset_selected_bindings',
    'Reset to Defaults',
    'reset_keyboard_bindings',
    'Keyboard Bindings (',
    ')',
    'Reset to Recommended',
    'reset_controller_bindings',
    'Start Game',
    'Set your loadout, then launch a new run when you are ready to hit the tracks.',
    'Practice Lane',
    'practice_lane',
    'Open Practice Setup, then run obstacle-only training with optional speed scaling and no economy pressure.',
    'events',
    'Open the live event hub for Daily High Score, Coin Meter, the login calendar, and daily rewards.',
    'missions_hub',
    'Review mission sets, quests, and achievement progress from a single progression hub.',
    'me',
    'Manage your active runner, hoverboard, upgrades, and collection bonuses.',
    'shop',
    'Spend banked coins on hoverboards, boosters, boxes, and your free daily gift.',
    'leaderboard',
    'Connect to the online leaderboard, browse top players, and inspect published run history.',
    'Spin the weekly special-item wheel up to two times each week after signing in.',
    'issue_reports',
    'Send a bug report through the online issue system and browse submitted reports by status.',
    'whats_new',
    'Hear the latest update notes, balance changes, and new features in this build.',
    'options',
    'Adjust audio, speech, controls, and accessibility settings before your next run.',
    'howto',
    'Browse movement, hazard, reward, and progression guidance one topic at a time.',
    'learn_sounds',
    'Preview essential gameplay sounds so you can recognize danger, rewards, and powerups instantly.',
    'Check for Updates',
    'check_updates',
    'Search for a newer release and install it when an update is available.',
    'Exit',
    'Close the game and return to desktop.',
    'Update Required   ',
    ' -> ',
    'A newer version is available. Current version ',
    '. Latest version ',
    'Update Available   ',
    'A newer release is available. This source checkout reports version ',
    '. Latest release ',
    'Subway Surfers Blind Edition',
    'No release information is available.',
    'update-install',
    'Current version ',
    'Mission set complete. Permanent multiplier is now x{0}.',
    "Today's progress was reset. Word Hunt stayed complete because today's reward was already claimed.",
    'fortune_line',
    '{0}: Super Mystery Box. {1} hoverboard{2}.',
    '{0}: Super Mystery Box. {1} key{2}.',
    '{0}: Super Mystery Box. Headstart.',
    '{0}: Super Mystery Box. Score Booster.',
    '{0}: Super Mystery Box jackpot. {1} coins saved.',
    '{0}: Super Mystery Box. Permanent multiplier x{1}.',
    ': Super Mystery Box. ',
    ' coins saved.',
    'Word Hunt complete. Streak {0}. {1} coins saved.',
    'Word Hunt complete. Streak ',
    '. Super Mystery Box.',
    'Season Hunt reward. {0} coins saved.',
    'Season Hunt reward. Key.',
    'Season Hunt reward. Headstart.',
    'Not enough coins.',
    ' (',
    'Season reward for rank ',
    'just_connected',
    'season_imprint',
    'consumed_special_item_keys',
    ' unlocked.',
    '{0} is still locked.',
    '{0} is already active.',
    ' selected.',
    'Unlock the character before upgrading.',
    '{0} is already at max level.',
    ' upgraded to level ',
    '. Pickup duration ',
    '{0} is not ready yet.',
    '{0}. {1} coins saved.',
    '{0}. {1} key{2}.',
    '{0}. {1} headstart{2}.',
    '{0}. {1} score booster{2}.',
    '{0}. {1} hoverboard{2}.',
    '{0}. {1} event coins.',
    '{0}. Super Mystery Box.',
    ' reward is unavailable.',
    'Hoverboard purchased.',
    'Mystery box: {0} coins.',
    'Mystery box: {0} hoverboard{1}.',
    'Mystery box: {0} key{1}.',
    'Mystery box: {0} headstart{1}.',
    'Mystery box: {0} score booster{1}.',
    'Mystery box jackpot: {0} coins.',
    'vault_seal',
    '{0} bonus saved {1} extra coins.',
    'Vault Seal protected {0} coins.',
    'Overclock Key bonus: +{0} key.',
    'Quest ready: {0}.',
    'hoverboards_used',
    ' connected. Open Controls in Options to review bindings.',
    ' disconnected. Keyboard controls remain available.',
    'Control reassignment cancelled.',
    'Press the key or key combination for {0}, then hold for 3 seconds. Escape cancels.',
    'Press a button or stick direction on the ',
    ' for ',
    '. Press Escape to cancel.',
    'Ctrl + ',
    'Alt + ',
    'Shift + ',
    'Meta + ',
    'Hold ',
    ' for 3 seconds.',
    ' set to ',
    'gain',
    'state',
    'Wheel reward: ',
    'toggle_special_item:',
    'toggle_practice_speed_scaling',
    'begin_run',
    'wheel_item_info:',
    'claim_quest:',
    'opt_leaderboard_logout',
    'opt_gameplay_announcements',
    'opt_controls',
    'bind_keyboard:',
    'bind_controller:',
    'leaderboard_cycle_period',
    'leaderboard_cycle_difficulty',
    'leaderboard_player:',
    'leaderboard_info',
    'leaderboard_run:',
    'issue_cycle_status',
    'issue_report:',
    'issue_submit_confirm',
    'copy_info_line',
    'copy_info_all',
    'buy_hoverboard',
    'buy_box',
    'buy_headstart',
    'buy_score_booster',
    'open_character_upgrades',
    'item_upgrade_open:',
    'item_upgrade_status_info:',
    'item_upgrade_effect_info:',
    'character_open:',
    'character_status_info:',
    'character_perk_info:',
    'character_select:',
    'character_upgrade:',
    'board_open:',
    'board_status_info:',
    'board_power_info:',
    'board_select:',
    'board_active_info:',
    'collection_info:',
    'character_active_info:',
    'character_max_info:',
    'achievement:',
    'howto:',
    'resume',
    'pause_options',
    'to_main',
    'confirm_to_main',
    'cancel_to_main',
    'confirm_leaderboard_logout',
    'cancel_leaderboard_logout',
    'publish_confirm_yes',
    'publish_confirm_no',
    'confirm_purchase_yes',
    'confirm_purchase_no',
    'confirm_exit',
    'cancel_exit',
    'revive',
    'game_over_info_',
    'leaderboard_connect',
    '{0} profile loaded.',
    'suspicious',
    'Bug report submitted. Status: Investigating. {0} submissions remaining today.',
    'item_label',
    'reauth_required',
    '{0} Showing the last downloaded leaderboard.',
    '{0} Showing the last downloaded bug reports.',
    'issue_',
    'unsupported_request',
    'Sign in from Options, Set User Name, before opening Wheel Spin.',
    'Sign in required.',
    'No wheel spins left this week.',
    'This special item is not unlocked yet.',
    'Updating ',
    '...',
    'Sign in from Options, Set User Name, before opening the leaderboard.',
    'Refresh',
    'Score {0}',
    'Coins {0}',
    'Time {0}',
    'Loading ',
    'Refreshing leaderboard...',
    'Season Rank: {0}',
    'leaderboard_profile_info',
    'Published Runs: {0}',
    'Active Days: {0}',
    'Recent Avg Score: {0}',
    'Recent Avg Coins: {0}',
    'Recent Avg Play Time: {0}',
    'Recent Avg Distance: {0} meters',
    'Best Score Improvement: +{0}',
    'Latest Score: {0}',
    'Latest Coins: {0}',
    'Latest Play Time: {0}',
    'Latest Difficulty: {0}',
    'Latest Status: {0}',
    'Best Score: {0}',
    'Best Coins: {0}',
    'Best Play Time: {0}',
    'Best Difficulty: {0}',
    'Best Status: {0}',
    'T',
    'Verification: {0}',
    'leaderboard_run_info',
    'Distance: {0} meters',
    'Clean Escapes: {0}',
    'Revives Used: {0}',
    'Death Reason: {0}',
    'Game Version: {0}',
    'Published At: {0}',
    'User name and password are required.',
    'account_sync',
    'No message written yet.',
    'Report an Issue',
    'Submit Report',
    'Loading bug reports...',
    'No more pages in that direction.',
    'Created: ',
    'Sign in from Options, Set User Name, before submitting a bug report.',
    'message',
    'Bug Report Message',
    'Enter a number between 1 and 10000.',
    'Hazard target must be between 1 and 10000.',
    'Issue title is required.',
    'Issue message is required.',
    'Practice Lane runs cannot be published to the leaderboard.',
    'username',
    'Output device set to {0}.',
    'Requested output device unavailable. Using ',
    'Score booster active. Multiplier starts at x{0}.',
    'intro_ui',
    ' {0} active with bonus multiplier.',
    'speed scaling on',
    'fixed speed',
    'Practice Lane started. {0}. Clear {1} hazards to complete.',
    'Returned to main menu',
    'Play time: {0}.',
    'hyper_sneakers',
    'Hoverboard is disabled in Practice Lane.',
    'Hoverboard limit reached. You can use {0} per run.',
    'No hoverboards available.',
    '{0} hoverboard active.',
    '{0} hoverboard active. {1}.',
    '{0:.0f} meters',
    'Practice progress {0} of {1}. {2} hazards left.',
    'Practice Lane complete. Cleared ',
    ' hazards.',
    'Practice complete. Hazards cleared: ',
    'hover_active',
    'super_sneakers',
    'magnet_echo',
    'Magnet expired.',
    'quiet_jet',
    'Jetpack expired.',
    'Score boost expired.',
    'Pogo stick expired.',
    'chain_saver',
    'chain_saver_used',
    '{0} coins',
    'Key collected. Total keys: ',
    'Letter {0}.',
    'Letter ',
    ' letters left.',
    'Season token. Reward unlocked.',
    'Season token. Total {0}.',
    'Season token. ',
    'Headstart reward: magnet.',
    'Magnet.',
    'Jetpack.',
    'Headstart reward: double score.',
    'Double score.',
    'Headstart reward: super sneakers.',
    'Super sneakers.',
    'You can revive for ',
    'Revive limit reached. Only {0} revives work in one run.',
    'Not enough keys.',
    'player_death_cam',
    'player_death_fall',
    'Run over. Score ',
    'spatial_{0}',
    'phantom_step',
    'Phantom Step dodge.',
    'Hoverboard destroyed.',
    'impact_foam',
    'impact_foam_used',
    'Impact Foam consumed.',
    'crowd_jammer',
    'risk_converter',
    'Select a sound to hear its gameplay cue.',
    'Multiplier: x',
    'Speed: ',
    'Boards: ',
    'Keys: ',
    '   [Practice Lane ',
    '   Left: ',
    ']',
    '{0}/done',
    '   Word Hunt: ',
    ' / ',
    '   Season Hunt: ',
    'whats_new_fallback',
    'Resume',
    'Return to Main Menu',
    'End Run',
    'end_run',
    'Score: 0',
    'game_over_info_score',
    'Coins: 0',
    'game_over_info_coins',
    'Play Time: 00:00',
    'game_over_info_time',
    'Death reason: Run ended.',
    'game_over_info_reason',
    'server_status_info',
    'Connect to the server to load leaderboard entries.',
    'Status: All Statuses',
    'Connect to the server to load bug reports.',
    'issue_info',
    'Page 1 of 1',
    'issue_page_info',
    'Previous Page',
    'Next Page',
    'On',
    'Off',
    'spins_remaining',
    'max_spins',
    'wheel_item_info:{0}',
    'Begin Practice',
    'Begin Run',
    'item_upgrade_open:{0}',
    'character_open:{0}',
    'board_open:{0}',
    'collection_info:{0}',
    'Mini Mystery Box: ',
    'Not enough Event Coins. ',
    ' needed, ',
    ' available.',
    ' is already unlocked.',
    'Permanent Multiplier: x',
    'howto:{0}',
    'Copy All',
    'achievement:{0}',
    'Achievement unlocked: ',
    'Collection complete: ',
    'Active Input: ',
    'Binding Profile: ',
    'Reset ',
    'bind_keyboard:{0}',
    'bind_controller:{0}',
    'Source builds cannot install updates automatically. Opening the release page.',
    'Source builds cannot install updates automatically.',
    '{0} Open the release page to download the new build.',
    'Hit train',
    'Hit low obstacle',
    'Hit high obstacle',
    'Hit bush',
    'Mission set complete. Permanent multiplier is now x',
    ' hoverboard',
    '{0}: Super Mystery Box. Jetpack.',
    ': Super Mystery Box. Headstart.',
    ': Super Mystery Box. Score Booster.',
    'ui4',
    ': Super Mystery Box jackpot. ',
    ': Super Mystery Box. Permanent multiplier x',
    'Season Hunt reward. ',
    'pending_rewards',
    '{0} seasonal rewards were delivered.',
    ' is still locked.',
    ' is already active.',
    ' is already at max level.',
    ' is not ready yet.',
    ' headstart',
    ' score booster',
    ' event coins.',
    'Mystery box: ',
    ' coins.',
    'Mystery box jackpot: ',
    ' bonus saved ',
    ' extra coins.',
    'Vault Seal protected ',
    'Overclock Key bonus: +',
    ' key.',
    'Quest ready: ',
    'Press the key or key combination for ',
    ', then hold for 3 seconds. Escape cancels.',
    'unicode',
    'Only one non-modifier key can be assigned in one binding.',
    'APPACTIVE',
    'device_index',
    'instance_id',
    'Daily High Score reward',
    'Coin Meter chest',
    'Free Daily Gift',
    'Daily Login reward',
    'Special server-side run effect.',
    'Sneaker Meter reward',
    '{0}. {1} sneakers added.',
    'Current input is {0}. {1}.',
    'Keyboard bindings reset to defaults.',
    '{0} bindings reset to recommended defaults.',
    'Update files are ready. Restart the game to finish applying them.',
    'Unable to open the release page.',
    'Selected line copied to clipboard.',
    '{0}. {1}.',
    '{0}. {1} Current perk: {2}.',
    '{0} is already the active board.',
    'complete',
    'in progress',
    '{0}. {1} {2} of {3}. Bonus: {4}. Status: {5}.',
    '{0} is already your active character.',
    'Unlock {0} before upgrading.',
    'Please wait for the current server request to finish.',
    ' profile loaded.',
    'Account created.',
    'Signed in.',
    'high_score',
    'board_rank',
    'New personal best. Leaderboard rank {0}.',
    'New personal best.',
    '{0} Run flagged as suspicious.',
    'Run published and flagged as suspicious.',
    'Bug report submitted. Status: Investigating. ',
    ' submissions remaining today.',
    '{0} {1}.',
    ' Showing the last downloaded leaderboard.',
    ' Showing the last downloaded bug reports.',
    'leaderboard_player:{0}',
    'No published runs were found for the current filters.',
    'verification_status',
    'Score ',
    'Coins ',
    'Time ',
    'summary',
    'latest_run',
    'best_run',
    'history',
    'Season Rank: ',
    'Published Runs: ',
    'Active Days: ',
    'Recent Avg Score: ',
    'Recent Avg Coins: ',
    'Recent Avg Play Time: ',
    'Recent Avg Distance: ',
    ' meters',
    'Best Score Improvement: +',
    'Latest Score: ',
    'Latest Coins: ',
    'Latest Play Time: ',
    'Latest Difficulty: ',
    'Latest Status: ',
    'Best Score: ',
    'Best Coins: ',
    'Best Play Time: ',
    'Best Difficulty: ',
    'Best Status: ',
    'leaderboard_run:{0}',
    'verification_reasons',
    'Verification: ',
    'Distance: ',
    'Clean Escapes: ',
    'Revives Used: ',
    'Death Reason: ',
    'Game Version: ',
    'Published At: ',
    'Review Note: {0}',
    'Subway Surfers Blind Leaderboard',
    'Enter your user name and password. If the account does not exist yet, it will be created.',
    'Unknown date',
    'No bug reports were found for the current filter.',
    'Editing cancelled.',
    'Practice Hazard Target',
    'Output device set to ',
    'No SAPI voices available.',
    'Score booster active. Multiplier starts at x',
    'intro_chase',
    'intro_spray_once',
    ' active with bonus multiplier.',
    ' {0} active.',
    'Practice Lane started. ',
    '. Clear ',
    ' hazards to complete.',
    'Run started. {0} active. {1} board selected.{2} Headstart active for {3} charge{4}.',
    'Run started. {0} active. {1} board selected.{2} Center lane.',
    'Coins collected: {0}.',
    'Play time: ',
    'afterimage_dash',
    'Hoverboard limit reached. You can use ',
    ' per run.',
    ' hoverboard active.',
    ' hoverboard active. ',
    'combo_battery',
    'Practice progress ',
    ' hazards left.',
    'quiet_jet_buffer',
    ' coins',
    'Mystery box: hoverboard.',
    'Season token. Total ',
    'Revive limit reached. Only ',
    ' revives work in one run.',
    'spatial_',
    'spawn_calm',
    'risk_bloom',
    'near_{0}',
    'Update required before you can continue.',
    'Release Notes:',
    '/done',
    'whats_new_title',
    'yes',
    'no',
    'toggle_special_item:{0}',
    'Download {0} percent.',
    ' Open the release page to download the new build.',
    'Mission complete: {0}.',
    ': Super Mystery Box. Jetpack.',
    'seconds_remaining',
    'Reward',
    'Loading current season reward...',
    ' seasonal rewards were delivered.',
    'Headstart purchased.',
    'mod',
    'h',
    'APPINPUTFOCUS',
    'APPMOUSEFOCUS',
    'No headstarts available.',
    'No score boosters available.',
    'That quest is not ready yet.',
    ' sneakers added.',
    'Current input is ',
    ' bindings reset to recommended defaults.',
    'No controller connected.',
    'Restarting to apply the update.',
    'Opening the release page.',
    ' Current perk: ',
    ' is already the active board.',
    '. Bonus: ',
    '. Status: ',
    ' is already your active character.',
    'Unlock ',
    ' before upgrading.',
    'leaderboard-{0}',
    'period',
    'entries',
    'total_players',
    'history_total',
    'created',
    'New personal best. Leaderboard rank ',
    ' Run flagged as suspicious.',
    'status',
    'total_reports',
    'offset',
    'submissions_remaining_today',
    'reward',
    'Review Note: ',
    'Untitled issue',
    'issue_report:{0}',
    ' active.',
    'Run started. ',
    ' active. ',
    ' board selected.',
    ' Headstart active for ',
    ' charge',
    ' Center lane.',
    'Coins collected: ',
    'afterimage_window',
    'streak_guard',
    '.0f',
    'Chain Saver activated.',
    'S',
    '2X',
    '?',
    'P',
    'Mystery box: multiplier {0}.',
    'near_',
    'extract',
    'Progress: {0}%',
    'Use Up and Down to select a line. Press Enter to copy it. Copy All is at the end.',
    'Claimed Today',
    'Download ',
    ' percent.',
    'Mission complete: ',
    'reward_label',
    'reward_preview',
    'season_name',
    'season_key',
    'reward_amount',
    'Score booster purchased.',
    'leaderboard-',
    'enabled',
    'Unranked',
    'submission_id',
    'afterimage_charges',
    'Mystery box: multiplier ',
    'Mystery box: key.',
    'Progress: ',
    'id',
    'rank',
    'published_at',
    'created_at',
    'reporter_username',
    'reported_by',
    'Mystery box: headstart.',
    'season_imprint_bonus',
    'published_runs_total',
    'active_days',
    'recent_average_score',
    'recent_average_coins',
    'recent_average_play_time_seconds',
    'recent_average_distance_meters',
    'best_improvement_score',
    'report_id',
    'Mystery box: score booster.',
    'Selected item',
    'Edit title and message here. Windows text input opens inside this game window.',
    'reward_kind',
    'item_key',
    'Speech enabled',
    'Speech disabled',
    'Press a controller input for {0}. Escape cancels.',
    'Press key(s) for {0}, then hold 3 seconds. Escape cancels.',
    'Keep holding keys... {0:.1f}s left for {1}. Escape cancels.',
    'Press a controller input for ',
    '. Escape cancels.',
    'Press key(s) for ',
    ', then hold 3 seconds. Escape cancels.',
    'Keep holding keys... ',
    's left for ',
    '{0}::{1}',
    'openal',
    'alsoft.ini',
    '[general]\nstereo-mode = headphones\nhrtf = true\nsources = 128\nslots = 16\n',
    'ALSOFT_CONF',
    '::',
    '_mono',
    '{0}_{1}{2}{3}',
    'openal_cache',
    '{0}_{1}{2}',
    'sound',
    '{0}.{1}.{2}.tmp',
    'PROGRAMDATA',
    'C:\\ProgramData',
    '.tmp',
    'spatial',
    'direct',
    'SubwaySurfersBlindEdition',
    'wb',
    'playing',
    'VireonInteractive',
    '{0}::{1}::{2}',
    'Item upgrade keys must be unique.',
    'Coin Magnet',
    'Pulls nearby coins into your lane while it is active.',
    'Jetpack',
    'Lifts you above hazards and collects airborne coin lines automatically.',
    '2X Multiplier',
    'Temporarily doubles the score multiplier earned during a run.',
    'Super Sneakers',
    'Boosts jump height so low barriers and bushes are easier to clear.',
    'Item upgrade key must be non-empty.',
    'Item upgrade name must be non-empty.',
    '{0} must define one more duration than upgrade cost.',
    '{0} upgrade costs must be positive.',
    '{0} upgrade costs must be sorted from low to high.',
    '{0} durations must be positive.',
    '{0} durations must be sorted from low to high.',
    ' must define one more duration than upgrade cost.',
    ' upgrade costs must be positive.',
    ' upgrade costs must be sorted from low to high.',
    ' durations must be positive.',
    ' durations must be sorted from low to high.',
    'ping',
    'login',
    'claimed_reward_ids',
    'sync_account',
    'spin_weekly_wheel',
    'set_special_item_loadout',
    'fetch_leaderboard',
    'fetch_profile',
    'fetch_issue_reports',
    'fetch_issue_report_detail',
    'submit_issue_report',
    'submit_score',
    'type',
    'payload',
    'PROCESSOR_IDENTIFIER',
    'missing_server_key',
    'server.json does not contain a server public key.',
    'connect_timeout',
    'Unable to connect to the leaderboard server.',
    'handshake_timeout',
    'Timed out while negotiating a secure session.',
    'hello_ack',
    'handshake_failed',
    'Server returned an invalid handshake response.',
    'Server did not supply a secure session identifier.',
    'password',
    'device_hash',
    'logout',
    'limit',
    'history_offset',
    'history_limit',
    'disconnected',
    'No active server connection is available.',
    'SOFTWARE\\Microsoft\\Cryptography',
    'MachineGuid',
    'ascii',
    'resume_session',
    'session_token',
    'request_timeout',
    'Leaderboard server did not respond in time.',
    'Disconnected from the leaderboard server.',
    'protocol',
    'ok',
    'server_error',
    'Leaderboard request failed.',
    'session_id',
    'server_nonce',
    'error_code',
    'Protocol message exceeds the maximum packet size.',
    'Protocol message must be a JSON object.',
    'Expected a handshake packet.',
    'client_public_key',
    'client_nonce',
    'hello',
    'big',
    'Invalid base64 payload.',
    'Unable to encode protocol message.',
    'Unable to decode protocol message.',
    'Invalid private key.',
    'Invalid public key.',
    'Nonce prefixes must be exactly four bytes long.',
    'Encrypted packet exceeds the maximum packet size.',
    'Expected an encrypted packet.',
    'Encrypted packet is incomplete.',
    'Encrypted packet counter is out of sequence.',
    'Unable to decrypt encrypted packet.',
    ',',
    'Lane',
    'Left lane',
    'Center lane',
    'Right lane',
    'BringWindowToTop',
    'SetForegroundWindow',
    'SetActiveWindow',
    'SetFocus',
    'cbSize',
    'hwndParent',
    'pszMessageText',
    'pszCaptionText',
    'hbmBanner',
    'Native Windows credentials are not available.',
    'Unable to unpack credentials returned by Windows.',
    'Unknown credential field requested.',
    'Credential dialog failed with error code {0}.',
    'Credential dialog failed with error code ',
    '\\',
    '{0}\\{1}',
    'WINFUNCTYPE',
    'Windows text input closed unexpectedly.',
    'Enter submits. Shift+Enter starts a new line. Escape cancels.',
    'Enter submits. Escape cancels.',
    'Only numbers are allowed. Enter submits. Escape cancels.',
    'STATIC',
    'EDIT',
    'Windows text input is not available in the current display mode.',
    'Unable to size the Windows text input controls.',
    'Unable to create Windows text input label controls.',
    'Unable to create the Windows text input field.',
    'Windows text input message loop failed.',
    'Windows text input is currently unavailable.',
    'Issue Input',
    'SURF',
    'TRAIN',
    'COINS',
    'BOARD',
    'TRACK',
    'BOOST',
    'MAGNET',
    'HOVER',
    'METRO',
    'SPRAY',
    'DODGE',
    'SNEAK',
    'mission_bonus',
    '{0:04d}-{1:02d}',
    'Collect {target} coins',
    'Jump {target} times',
    'Roll {target} times',
    'Change lanes {target} times',
    'Collect {target} power-ups',
    'Open {target} mystery boxes',
    'coin_collector',
    'Coin Collector',
    'Collect 1000 total coins.',
    'dodger',
    'Dodger',
    'Change lanes 500 times.',
    'jumper',
    'Jumper',
    'Jump 300 times.',
    'roll_master',
    'Roll Master',
    'Roll 300 times.',
    'box_hunter',
    'Box Hunter',
    'Open 25 mystery or super boxes.',
    'survivor',
    'Survivor',
    'Reach 1500 meters in a single run.',
    'daily_streak',
    'Daily Streak',
    'Reach a Word Hunt streak of 3.',
    'season_grinder',
    'Season Grinder',
    'Collect 20 Season Hunt tokens.',
    '04d',
    '{0:04d}-q{1}',
    'Run {target} meters',
    'Use hoverboards {target} times',
    'Collect {target} coins this season',
    'Change lanes {target} times this season',
    'Collect {target} power-ups this season',
    'Run {target} meters this season',
    'Finish {target} runs this season',
    'Open {target} boxes this season',
    'Use hoverboards {target} times this season',
    'daily:practice_lane_complete',
    'Complete Practice Lane once',
    'daily_id',
    'daily_progress',
    'daily_claimed',
    'season_id',
    'season_progress',
    'season_claimed',
    'meter_stage',
    '-q',
    'season:{0}:{1}',
    'daily:{0}:{1}',
    'season:',
    'daily:',
    'host',
    'port',
    'server_public_key',
    'server_public_key_path',
    'connect_timeout_ms',
    'request_timeout_ms',
    'page_size',
    '127.0.0.1',
    'server/runtime/server_public_key.b64',
    'server.json',
    'jump now',
    'roll now',
    'turn left',
    'turn left now',
    'turn right',
    'turn right now',
    'right',
    'left',
    'turn {0}',
    'turn {0} now',
    'turn ',
    ' now',
    'inf',
    'play',
    'has_sound',
    'announcer_prompt',
    'single_train',
    'single_low',
    'single_high',
    'single_bush',
    'double_side_trains',
    'train_left_low_mid',
    'train_right_high_mid',
    'center_train_side_barrier',
    'center_train_side_barrier_alt',
    'stagger_jump_route',
    'stagger_roll_route',
    'triple_readable_split',
    'free',
    'blocked',
    '{0}:{1}:{2}',
    '2022-11-28',
    'Accept',
    'User-Agent',
    'X-GitHub-Api-Version',
    'application/vnd.github+json',
    '{0} Updater',
    '^\\s*v?(?P<major>\\d+)(?:\\.(?P<minor>\\d+))?(?:\\.(?P<patch>\\d+))?(?:[-+].*)?\\s*$',
    '[^A-Za-z0-9._-]+',
    '{0}.{1}.{2}',
    ' Updater',
    'https://api.github.com/repos/{0}/{1}/releases/latest',
    'https://github.com/{0}/{1}/releases',
    'major',
    'https://api.github.com/repos/',
    '/releases/latest',
    'https://github.com/',
    '/releases',
    'updates',
    'latest',
    'apply_update.cmd',
    '@echo off\nsetlocal\nset STAGE={0}\nset TARGET={1}\nset ARCHIVE={2}\nset RETRIES=0\nset MAX_RETRIES={3}\n:retry\npowershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference = \'Stop\'; Copy-Item -LiteralPath \'%STAGE%\\*\' -Destination \'%TARGET%\' -Recurse -Force" >nul 2>nul\nif errorlevel 1 (\n  set /a RETRIES=%RETRIES%+1\n  if %RETRIES% GEQ %MAX_RETRIES% exit /b 1\n  timeout /t 1 /nobreak >nul\n  goto retry\n)\nrmdir /S /Q "%STAGE%" >nul 2>nul\ndel /Q "%ARCHIVE%" >nul 2>nul\nstart "" "{4}"\nexit /b 0\n',
    'update_available',
    'minor',
    'patch',
    'up_to_date',
    'You already have the latest version.',
    'Extracting update package.',
    'Update installed. Restart the game to finish applying it.',
    '._',
    'main.py',
    '@echo off\nsetlocal\nset STAGE=',
    '\nset TARGET=',
    '\nset ARCHIVE=',
    '\nset RETRIES=0\nset MAX_RETRIES=',
    '\n:retry\npowershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference = \'Stop\'; Copy-Item -LiteralPath \'%STAGE%\\*\' -Destination \'%TARGET%\' -Recurse -Force" >nul 2>nul\nif errorlevel 1 (\n  set /a RETRIES=%RETRIES%+1\n  if %RETRIES% GEQ %MAX_RETRIES% exit /b 1\n  timeout /t 1 /nobreak >nul\n  goto retry\n)\nrmdir /S /Q "%STAGE%" >nul 2>nul\ndel /Q "%ARCHIVE%" >nul 2>nul\nstart "" "',
    '"\nexit /b 0\n',
    'The latest release data was invalid.',
    'Version {0} is available.',
    'No ZIP update package was found in the latest release.',
    'cmd.exe',
    '/c',
    '.zip',
    'release_{0}_',
    'subway_blind_update_',
    'Update check failed with HTTP {0}.',
    'Unable to contact GitHub Releases.',
    'Version ',
    ' is available.',
    'Unable to download the update package.',
    'Unable to extract the update package.',
    'CREATE_NO_WINDOW',
    'tag_name',
    'name',
    'Extracting update package. {0} percent.',
    '..',
    'release_',
    'no_releases',
    'No published releases were found.',
    'Update check failed with HTTP ',
    'Content-Length',
    'Extracting update package. ',
    'Downloading update package. {0} percent.',
    'browser_download_url',
    'Downloading update package. ',
    'size',
    'html_url',
    'body',
    'content_type',
    'Subway Surfers Blind',
    '1.1.5',
    'oguzhanproductions',
    'subway_surfers_blind',
)


def sx(index: int) -> str:
    return _STRING_BANK[index]
